### ISSUE TITLE
Use `openapi-types`

### ISSUE THREAD

**Issue by czabaj** [manifoldco/swagger-to-ts#182]
This is just friendly advice. You can use https://www.npmjs.com/package/openapi-types , no need to create your own (they have also OPenAPIV3 types) 😉

**Comment by RinatGumarov** [comment]
How do you generate types with this package for your swagger api?

**Comment by dangodev** [comment]
Thanks, @czabaj, that’s good to know about 🙂

I’ll see what adding those adds, if anything, and if it helps for the Swagger V3 addition. Though the types in this project are minimal and partial, because this library doesn’t need to know about all the features of the spec to transform it; only a couple keys that it uses to build the types. It made sense to me to only write a few lines of the OpenAPI types this library cares about. You better believe I’d never try to recreate the full spec in TS! That’d be all my OSS freetime right there.

**Comment by czabaj** [comment]
Message received. Closing
