### ISSUE TITLE
How about export all of the properties of definitions?

### ISSUE THREAD

**Issue by FourF-src** [manifoldco/swagger-to-ts#281]
After upgrade to V2, definitions should be used by `definitions['property']`. It seems something odd because people prefer to using definitions in form of `definitions.property` or 
``` typescript
import {property} from 'typing.ts'; 
let a:property;
```

Therefore, could you kindly export the type alias of these prosperities? Just by adding some codes like 
```typescript
export type property = definition['property'];
```  
 😊

**Comment by drwpow** [comment]
This is something I’d encourage you to do yourself, because it actually can’t be handled by the library. In your example, yes, `property` could be exported because it’s simple. However, the OpenAPI schema lets you have many other characters not safe for JS references, such as `My.Property` or `123`. That means if we started exporting these names, we’d have to transform them into JS-safe names, and that’s a rabbit hole.

Instead, I’d recommend having some central `./types/swagger.ts` file in your app where you create/manage all the shorthands yourself, and export it to the rest of your app. That way you’re never blocked by this library if it didn’t generate it correctly.

**Comment by FourF-src** [comment]
Thank you for reply. Ok, I will create alias by myself.
